export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const MEETING_REPOSITORY = Symbol('MEETING_REPOSITORY');
export const PARTICIPANT_REPOSITORY = Symbol('PARTICIPANT_REPOSITORY');
export const CHAT_REPOSITORY = Symbol('CHAT_REPOSITORY');
