export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const MEETING_REPOSITORY = Symbol('MEETING_REPOSITORY');
export const PARTICIPANT_REPOSITORY = Symbol('PARTICIPANT_REPOSITORY');
export const CHAT_REPOSITORY = Symbol('CHAT_REPOSITORY');
export const AGENDA_REPOSITORY = Symbol('AGENDA_REPOSITORY');
export const POLL_REPOSITORY = Symbol('POLL_REPOSITORY');
export const REACTION_REPOSITORY = Symbol('REACTION_REPOSITORY');
